name: CI

on:
  push:
    brances: master

  workflow_dispatch:

jobs:
  display:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        name: Отображение персонализированной переменной.
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          echo "Токен успешно загружен: $DISCORD_TOKEN"