name: Secrets, Tokens etc.

on:
  push:
    branches: master

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
      - name: Токен Discord-Бота.
        run: |
          echo "Токен успешно загружен: $DISCORD_TOKEN"
